### ISSUE TITLE
Missing cat_training_data.sh in neural-tagger

### ISSUE THREAD

**Issue by shijie-wu** [sigmorphon/contextual-analysis-baseline#1]
In `neural-tagger/README.md`, there is a `cat_training_data.sh` file.

> We also provide code to perform jackknifing for eliminating exposure bias when training the lemmatizer. To generate the jackknifed training data, provide the additional argument `--jackknifing` and use `cat_training_data.sh` to create the combined training file.

But it seems the file is missing.

**Comment by aryamccarthy** [comment]
@chaitanyamalaviya would know more about this.

**Comment by chaitanyamalaviya** [comment]
Fixed.

**Comment by aryamccarthy** [comment]
Thanks, Chaitanya!
